# Utiliser une image Nginx comme base
FROM mysql:alpine

# Copier le contenu du frontend dans le répertoire de Nginx
COPY . /usr/share/nginx/html

# Exposer le port 80 pour accéder au frontend
EXPOSE 80
